---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgASd5sC0a28Ykv6pYH9N7XEUemmb+L2tVfE+AeUSicKTIBaB9EIHCeJ5XvWCy721VoLB81TghhXc/5vaNLMfZdbcHoyfM5n+8qC22bW9LKoPX1Vc/8aBicbBLPdOawoq9ELB4/on9FfM03EvVambD8t0N3ivqsPLNrRSRzFpeOmb75Onwl13xO18eYelGPbX0C1+v1mWzY1r4qRIWChoxe8VFpTG//3ZYTj28aUaZqbVR2x5YbIV9DUUx88ZdkBq2y0HZYw2UVyjqHUANmHypxyYQkx9C4yNYNYReafMVI8q6sgdPUKv/AVPkVQsBRWmKfPImKXTWv0LeK2EpDkNht3Ea9sEURz0SmbASid1svXkl8ASAqsPAcXF7SLFyXYQv6haqSuTD5Pe2qQcZzYiZmHRjSHShIFQTA1aHON5J0wZ9Sr11yBKfNWpDC+cCWsMbZks7dHBOr18UA+//I4Dv3IcV6lnywMpTwXY9N4BxMLstS3eRlPsy9tZ+ARs/bhO2N8eXFF+TwYOt089R6D3b1i/dBBuRPTeRKlRns8YOGR6Tja7sdJ8BKPB19UffpXZS4rojWMGV7KfmRlXl+v9qu34OFOr1RHXxizWCybJlKKEhcACfOEwjLCrnbMInWcRl6kulEOfDsTwGGf3PebtWor9YG/2N7a4sv43sfBlZJp1K9jQAqC+Kjo13DGKWx+uePltIwoeGF63Q==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque
