---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgArfrlrWe2Ak12H7bVOjnMTcRb09sgfRA0yDpgTY0SPX4/OD5nZEMjjTJWCYmGwX+KLLeP/DMTebfzXEYsy41yAnJvqe1frtQS6haaPiR1pK8T8bSU5ImwD1zgZbA37JWfsvX9Un/4ysEX8TyyYZxm/FgaZ0ZTOyRRLSsS+OPgMEAxkXsS/K3n+LhmH4f2QMux68Voqc4g2ZDPs6nT0ESzSJBU+jyxKg+Ulx0kx4UNcNUEeiMhmVSUX5WqcFyoOjCKED4ZX/K2Ey/4AFXHrL5u4t86i4zVpYV0PR+fDTX6W4nrK24sYXGp8rn4iXa/rPde5JU43kF/UerR6v7GOewGE1+TPfLJCNMfp9cFcvs0xzDzOzG4ibgRtjuLC1NK+9F4bDA0Mk2kwBvih7vJ+RnsFeYdJPM4c7Lo+r4NzMqVBxBTpRYKvlJOC/wz38YBRaRo80NdPjPlQUyA2DRWKz1nWrE9EpKCi4eaHXGoIE09XeiMLPMxh9CsfURyKr6UCsYuMgvLJX7ai7Bzr7UoJufcteJP43UwOg3ItVuZdHlbTi540OMM/CK5khYrWl0v5gaAJ/AWHwmOQ0Ld01r3oV/iphEx/EoglTm8ILyRNm8DK0tIVFBZnmCOnRTF17nYz0jYjUBwTBK8PSDmlAS66FtaE+WYaInlETEO1q2ZJe0GQbXsFUblxL2UaL7Y55gysM6nHgbUZk9P22A==
    DB_USER: AgCIfbX74Lf0WYf5c5/d7V8loaCIs8EuqULL6f/GSWOMJh5IGnx52keacVf6Krmw2qjXzvL8+AvDgosIzApLa3sauEgxp0gbaTQz3z6KOdOI3ltXv92gkoUHyzi5Gcv2jWX/WiqPJBJcaXZ6yM9qFVL3o7Zlx5yRDtVHmCqFwh0LU5sJCc0VeZd4IDb6s3h/O+Aeq7y8wixAkLz3TvT2CZnPFuNTazi9mrbegfJr+PKBBUQC9veZrF3kCU5ceyX/nq/mnduo7g1siXONRew+UGDjcsF9+g7ZHEZgCfn4/5jlfso+H0nhlLSeTFk7o2stYbLlKAHSnSGJtKU9zcohm6ghuMhAGzj1rOSro2xDBhKlA6chbQsaADOj7c8vFpisADK7Ek2rPVV6k9Y7NAgaP/x83LfSvisG4cq2JjWShgRAahUMilDnBys3azOj6ey+5wTtScAOppSKJUNrW0EocuUIQzJeuLeSMuaxoQq0LUlXWUE4e8yl8CdIqDOEg8RfGE6osaWq+Q7WcuieGe28vwR0RqjqIY1TtBTFdio9NWCa7+/01Dgqfmdy1No8QxBKb9jUI/ppUz4MTQxyOBfx0xQ7gRIATVDT7Rxc29GYw6GM37fRo83u0NlK6mD+moJAH/3Zrwlj3xiuc3au625YAOloYadYQYNv2631VLErx+J9ph2BVCGzcNT3cqWr3IjYydjPnFs0Z0GbAw==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque
